// civs.js
const civs = [
  { name: "Britons", dlc: false },
  { name: "Franks", dlc: false },
  { name: "Goths", dlc: false },
  { name: "Teutons", dlc: false },
  { name: "Japanese", dlc: false },
  { name: "Chinese", dlc: false },
  { name: "Byzantines", dlc: false },
  { name: "Persians", dlc: false },
  { name: "Saracens", dlc: false },
  { name: "Vikings", dlc: false },
  { name: "Mongols", dlc: false },
  { name: "Celts", dlc: false },
  { name: "Spanish", dlc: false },
  { name: "Aztecs", dlc: false },
  { name: "Mayans", dlc: false },
  { name: "Huns", dlc: false },
  { name: "Koreans", dlc: false },
  { name: "Turks", dlc: false },
  { name: "Italians", dlc: false },
  { name: "Incas", dlc: false },
  { name: "Magyars", dlc: false },
  { name: "Slavs", dlc: false },
  { name: "Portuguese", dlc: false },
  { name: "Ethiopians", dlc: false },
  { name: "Malians", dlc: false },
  { name: "Berbers", dlc: false },
  { name: "Khmer", dlc: false },
  { name: "Malay", dlc: false },
  { name: "Vietnamese", dlc: false },
  { name: "Bulgarians", dlc: false },
  { name: "Cumans", dlc: false },
  { name: "Lithuanians", dlc: false },
  { name: "Tatars", dlc: false },
  { name: "Burgundians", dlc: false },
  { name: "Sicilians", dlc: false },
  { name: "Poles", dlc: false },
  { name: "Bohemians", dlc: false },
  { name: "Dravidians", dlc: false },
  { name: "Bengalis", dlc: false },
  { name: "Gujaras", dlc: false },
  { name: "Hindustanis", dlc: false },
  { name: "Armenians-DLC", dlc: true },
  { name: "Georgians-DLC", dlc: true },
  { name: "Shu-DLC", dlc: true },
  { name: "Wei-DLC", dlc: true },
  { name: "Wu-DLC", dlc: true },
  { name: "Jurchens-DLC", dlc: true },
  { name: "Khitans-DLC", dlc: true }
];

export default civs;
