// civs
export const civs = [
  { name: "Britons", dlc: false },
  { name: "Franks", dlc: false },
  { name: "Goths", dlc: false },
  { name: "Teutons", dlc: false },
  { name: "Japanese", dlc: false },
  { name: "Chinese", dlc: false },
  { name: "Byzantines", dlc: false },
  { name: "Persians", dlc: false },
  { name: "Saracens", dlc: false },
  { name: "Vikings", dlc: false },
  { name: "Mongols", dlc: false },
  { name: "Celts", dlc: false },
  { name: "Spanish", dlc: false },
  { name: "Aztecs", dlc: false },
  { name: "Mayans", dlc: false },
  { name: "Huns", dlc: false },
  { name: "Koreans", dlc: false },
  { name: "Turks", dlc: false },
  { name: "Italians", dlc: false },
  { name: "Incas", dlc: false },
  { name: "Magyars", dlc: false },
  { name: "Slavs", dlc: false },
  { name: "Portuguese", dlc: false },
  { name: "Ethiopians", dlc: false },
  { name: "Malians", dlc: false },
  { name: "Berbers", dlc: false },
  { name: "Khmer", dlc: false },
  { name: "Malay", dlc: false },
  { name: "Vietnamese", dlc: false },
  { name: "Bulgarians", dlc: false },
  { name: "Cumans", dlc: false },
  { name: "Lithuanians", dlc: false },
  { name: "Tatars", dlc: false },
  { name: "Burgundians", dlc: false },
  { name: "Sicilians", dlc: false },
  { name: "Poles", dlc: false },
  { name: "Bohemians", dlc: false },
  { name: "Dravidians", dlc: false },
  { name: "Bengalis", dlc: false },
  { name: "Gujaras", dlc: false },
  { name: "Hindustanis", dlc: false },
  { name: "Armenians", dlc: true },
  { name: "Georgians", dlc: true },
  { name: "Shu", dlc: true },
  { name: "Wei", dlc: true },
  { name: "Wu", dlc: true },
  { name: "Jurchens", dlc: true },
  { name: "Khitans", dlc: true }
];

// maps
export const maps = [
    "African Clearing",
    "Alps 2.0",
    "Amazon Tunnel",
    "Arena",
    "Big Freeze",
    "Black Forest",
    "Border Dispute",
    "Cambira 1.0",
    "Chaos Pit",
    "Cliffbound",
    "Crater",
    "Grand Bara",
    "Graveyards",
    "Hideout",
    "Kilimanjaro",
    "Land Nomad",
    "MegaRandom",
    "Michi",
    "Mountain Ridge",
    "QS Arena",
    "QS Blackforest",
    "Sherwood Forest",
    "Team Acropolis",
    "Two Rivers",
    "Valley",
    "Yucatan",
    "seafood Pie"
];